language: ruby
rvm:
  - 1.9.3
before_script:
  - "cp ./config/database.yml.example ./config/database.yml"
  - "mysql -e 'create database vish_test;'"
  - "mysql -e 'create database vish_recsys_test;'"
  - "mysql -e 'create database vish_production;'"
  - "mysql -e 'create database vish_recsys_production;'"
  - "mysql vish_recsys_test < db/recsys_db.sql"
  - "mysql vish_recsys_production < db/recsys_db.sql"
  - "bundle exec rake db:schema:load"
